[package]
name = "squark-stdweb"
version = "0.1.0"
authors = ["Satoshi Amemiya <amemiya@protonmail.com>"]

[dependencies]
squark = { "path" = "../squark" }
stdweb = "0.4.2"
serde_json = "1.0.13"
serde = "1.0.34"

[workspace]
members = ["examples/todomvc"]
