[package]
name = "squark"
version = "0.1.0"
authors = ["Satoshi Amemiya <amemiya@protonmail.com>"]
repository = "https://github.com/rail44/squark"
homepage = "https://github.com/rail44/squark"
license = "WTFPL"
readme = "../README.md"
keywords = ["web", "asmjs", "webasm", "javascript"]
categories = ["gui", "web-programming"]
description = "Virtual DOM implemention and application definition inspired from HyperApp"

[dependencies]
uuid = "0.6.2"
rand = { git = "https://github.com/rust-lang-nursery/rand.git", features = ["stdweb"] }
serde_json = "1.0.13"
